# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T10:33:17+00:00

from __future__ import annotations

from enum import Enum


class VersionNumber(Enum):
    integer_1 = 1


class Format(Enum):
    json = 'json'
    jsonp = 'jsonp'
    xml = 'xml'


class Zoom(Enum):
    integer_0 = 0
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3
    integer_4 = 4
    integer_5 = 5
    integer_6 = 6
    integer_7 = 7
    integer_8 = 8
    integer_9 = 9
    integer_10 = 10
    integer_11 = 11
    integer_12 = 12
    integer_13 = 13
    integer_14 = 14
    integer_15 = 15
    integer_16 = 16
    integer_17 = 17
    integer_18 = 18


class Layer(Enum):
    basic = 'basic'
    hybrid = 'hybrid'
    labels = 'labels'


class Style(Enum):
    main = 'main'
    night = 'night'


class Format4(Enum):
    png = 'png'
    jpg = 'jpg'
    jpeg = 'jpeg'


class Zoom1(Enum):
    integer_0 = 0
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3
    integer_4 = 4
    integer_5 = 5
    integer_6 = 6
    integer_7 = 7
    integer_8 = 8
    integer_9 = 9
    integer_10 = 10
    integer_11 = 11
    integer_12 = 12
    integer_13 = 13
    integer_14 = 14
    integer_15 = 15
    integer_16 = 16
    integer_17 = 17
    integer_18 = 18
    integer_19 = 19
    integer_20 = 20
    integer_21 = 21
    integer_22 = 22


class View(Enum):
    Unified = 'Unified'
    IN = 'IN'


class View2(Enum):
    Unified = 'Unified'
    IL = 'IL'
    IN = 'IN'


class Style2(Enum):
    main = 'main'


class TileSize(Enum):
    integer_256 = 256
    integer_512 = 512


class View4(Enum):
    Unified = 'Unified'
    IN = 'IN'


class Style3(Enum):
    main = 'main'
    night = 'night'


class Format6(Enum):
    jpg = 'jpg'
    png = 'png'


class Request(Enum):
    GetMap = 'GetMap'


class Srs(Enum):
    EPSG_3857 = 'EPSG:3857'
    EPSG_4326 = 'EPSG:4326'


class Format7(Enum):
    image_jpeg = 'image/jpeg'
    image_png = 'image/png'


class Layers(Enum):
    basic = 'basic'


class Styles(Enum):
    field_ = ''


class Service(Enum):
    WMS = 'WMS'


class Version(Enum):
    field_1_1_1 = '1.1.1'


class Request2(Enum):
    GetCapabilities = 'GetCapabilities'


class WmtsVersion(Enum):
    field_1_0_0 = '1.0.0'
